name: review
publish_to: none

environment:
  sdk: 3.10.4
  flutter: 3.38.5

dependencies:
  flutter:
    sdk: flutter

  review_core:
    path: '../core'

  review_impl:
    path: '../impl_foss'

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

