name: location_core
publish_to: none

environment:
  sdk: 3.10.4
  flutter: 3.38.5

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  navigation_core:
    path: '../../navigation/core'

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Shared Preferences - https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

