name: map_google
publish_to: none

environment:
  sdk: 3.10.4
  flutter: 3.38.5

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  map_core:
    path: '../core'

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

