name: navigation_core
publish_to: none

environment:
  sdk: 3.10.4
  flutter: 3.38.5

dependencies:
  flutter:
    sdk: flutter

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

